# Generated by Django 3.0.5 on 2020-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='image',
        ),
        migrations.AddField(
            model_name='upload',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='upload',
            name='images',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
